// Generated by CoffeeScript 1.6.3
(function() {
  var GatherResaultBox, Place, ResPoint,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  GatherResaultBox = (function(_super) {
    __extends(GatherResaultBox, _super);

    function GatherResaultBox(data) {
      var playerItem;
      GatherResaultBox.__super__.constructor.call(this, null);
      this.UI.title.J.text("采集结果");
      this.hideAcceptBtn();
      if (!data) {
        this.UI.content.J.text("这里已经没有东西了，下次再来吧。");
      } else {
        playerItem = data;
        this.UI.img.J.show();
        if (data.img) {
          this.UI.img.src = data.img.src;
        }
        this.UI.content.J.text("采集到了 " + data.dspName + " x 1");
      }
    }

    return GatherResaultBox;

  })(PopupBox);

  ResPoint = (function(_super) {
    __extends(ResPoint, _super);

    function ResPoint(place, tpl, data, index) {
      var isBoss, itemsData, monsterData, parts, position,
        _this = this;
      ResPoint.__super__.constructor.call(this, tpl);
      this.place = place;
      this.db = place.db;
      this.data = data;
      this.index = index;
      this.number = index + 1;
      this.pointText = "采集点" + (index + 1);
      this.UI.name.J.text(this.pointText);
      parts = data.split(" ");
      this.items = [];
      this.hasBoss = false;
      itemsData = parts[1];
      switch (itemsData) {
        case "none":
        case "null":
        case void 0:
          this.items = null;
          break;
        default:
          this.initItems(itemsData);
      }
      monsterData = parts[2];
      isBoss = parts[3];
      switch (monsterData) {
        case "none":
        case "null":
        case void 0:
          this.monsters = null;
          break;
        default:
          this.monsters = monsterData.split(',');
          if (isBoss) {
            this.UI.boss.J.show();
            this.hasBoss = true;
          } else {
            this.UI.monster.J.show();
          }
      }
      this.dom.number = index + 1;
      this.J.addClass("gp" + (index + 1));
      position = parts[0];
      this.J.css({
        left: position.split(",")[0] + "px",
        top: position.split(",")[1] + "px"
      }, this.dom.onclick = function(evt) {
        var box, text;
        evt.stopPropagation();
        if (_this.monsters && _this.monsters.length > 0) {
          text = _this.hasBoss ? "<strong>强大的怪物</strong>" : "怪物";
          box = new PopupBox("采集", "这里有" + text + "把守，需要打败他们才能采集。</br>要战斗吗？");
          box.setCloseText("算了");
          box.setAcceptText("来战");
          box.show();
          return box.on("accept", function() {
            return _this.emit("active", _this.active());
          });
        } else {
          return _this.emit("active", _this.active());
        }
      });
    }

    ResPoint.prototype.initItems = function(itemsData) {
      var name, _i, _len, _ref;
      _ref = itemsData.split(",");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        name = _ref[_i];
        if (!this.db.things.items.get(name)) {
          console.error("invailid item name", name);
        }
        this.items.push(new PlayerItem(this.db, name));
      }
      if (this.items.length > 0) {
        return this.UI.collect.J.show();
      }
    };

    ResPoint.prototype.handleEncounteringMonster = function() {
      var _this = this;
      if (!this.monsters || this.monsters.length === 0) {
        return false;
      }
      this.place.once("battleWin", function() {
        _this.monsters = null;
        _this.UI.monster.J.hide();
        return _this.UI.boss.J.hide();
      });
      return this.monsters;
    };

    ResPoint.prototype.active = function() {
      var i, item, monsters, newArr, _i, _len, _ref;
      console.log("active");
      monsters = this.handleEncounteringMonster();
      if (monsters) {
        return {
          type: "monster",
          monsters: monsters
        };
      } else {
        item = Utils.random(this.items);
        if (item) {
          newArr = [];
          _ref = this.items;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            i = _ref[_i];
            if (i !== item) {
              newArr.push(i);
            }
          }
          this.items = newArr;
          return {
            type: "item",
            item: item
          };
        }
      }
      this.UI.collect.J.hide();
      return {
        type: "empty"
      };
    };

    return ResPoint;

  })(Suzaku.Widget);

  Place = (function(_super) {
    __extends(Place, _super);

    function Place(area, db, name, data) {
      var self;
      this.area = area;
      this.db = db;
      this.name = name;
      this.data = data;
      Place.__super__.constructor.call(this);
      this.camera = new Camera();
      if (this.data.defaultX) {
        this.camera.x = this.data.defaultX;
      }
      this.drawQueueAddAfter(this.camera);
      this.initBg();
      this.initMenu();
      this.resPoints = [];
      this.currentX = 0;
      self = this;
    }

    Place.prototype.tick = function() {
      var changed, s;
      s = Utils.getSize();
      if (Key.up) {
        if (Key.shift) {
          this.camera.scale += 0.03;
        }
      }
      if (Key.down) {
        if (Key.shift) {
          this.camera.scale -= 0.03;
        }
      }
      if (Key.right) {
        this.currentX += 15;
        changed = true;
      }
      if (Key.left) {
        this.currentX -= 15;
        changed = true;
      }
      if (this.currentX < 0) {
        this.currentX = 0;
      }
      if (this.currentX > this.mainBg.width - s.width) {
        this.currentX = this.mainBg.width - s.width;
      }
      if (changed) {
        return this.camera.x = this.camera.getOffsetPositionX(this.currentX, this.mainBg);
      }
    };

    Place.prototype.initBg = function() {
      var bg, data, imgName, initLayer, _ref, _ref1;
      initLayer = function(layer, detail) {
        var name, value, _results;
        _results = [];
        for (name in detail) {
          value = detail[name];
          switch (name) {
            case "fixToBottom":
              _results.push(layer.fixToBottom());
              break;
            case "scale":
              console.log("scale", value);
              layer.transform.scale = value;
              _results.push(console.log(layer));
              break;
            default:
              _results.push(layer[name] = value);
          }
        }
        return _results;
      };
      this.floatBgs = [];
      this.bgs = [];
      if (this.data.bg) {
        _ref = this.data.bg;
        for (imgName in _ref) {
          data = _ref[imgName];
          bg = new Layer().setImg(Res.imgs[imgName]);
          console.log(bg, data);
          initLayer(bg, data);
          this.bgs.push(bg);
          this.camera.render(bg);
        }
      }
      if (this.data.floatBg) {
        _ref1 = this.data.floatBg;
        for (imgName in _ref1) {
          data = _ref1[imgName];
          bg = new Layer().setImg(Res.imgs[imgName]);
          console.log(bg, data);
          initLayer(bg, data);
          this.floatBgs.push(bg);
          this.camera.render(bg);
        }
      }
      this.mainBg = this.bgs[0];
      return console.log(this.mainBg);
    };

    Place.prototype.initMenu = function() {
      var index, moveCallback, mp, p, s, _i, _j, _len, _len1, _ref, _ref1,
        _this = this;
      s = Utils.getSize();
      this.menu = new Menu(Res.tpls['area-menu']);
      this.menu.J.addClass(this.name);
      this.menu.UI.title.J.text(this.data.name);
      moveCallback = function() {
        var x;
        x = _this.currentX;
        delete _this.camera.lock;
        if (x === 0) {
          _this.menu.UI['move-left'].J.removeClass("autohide").fadeOut(200);
        } else {
          _this.menu.UI['move-left'].J.addClass("autohide").fadeIn(200);
        }
        if (x === (_this.mainBg.width - s.width)) {
          return _this.menu.UI['move-right'].J.removeClass("autohide").fadeOut(200);
        } else {
          return _this.menu.UI['move-right'].J.addClass("autohide").fadeIn(200);
        }
      };
      this.menu.UI['move-right'].onclick = function(evt) {
        var x;
        evt.stopPropagation();
        console.log("right");
        _this.camera.lock = true;
        _this.currentX += 400;
        if (_this.currentX > _this.mainBg.width - s.width) {
          _this.currentX = _this.mainBg.width - s.width;
        }
        x = _this.camera.getOffsetPositionX(_this.currentX, _this.mainBg);
        if (x > _this.mainBg.width) {
          x = _this.mainBg.width;
        }
        return _this.camera.animate({
          x: x
        }, "normal", function() {
          return moveCallback();
        });
      };
      this.menu.UI['move-left'].onclick = function(evt) {
        var x;
        evt.stopPropagation();
        console.log("left");
        _this.camera.lock = true;
        _this.currentX -= 400;
        if (_this.currentX < 0) {
          _this.currentX = 0;
        }
        x = _this.camera.getOffsetPositionX(_this.currentX, _this.mainBg);
        return _this.camera.animate({
          x: x
        }, "normal", function() {
          return moveCallback();
        });
      };
      this.menu.UI.backpack.onclick = function(evt) {
        evt.stopPropagation();
        return _this.emit("showBackpack");
      };
      this.menu.dom.onclick = function(evt) {
        var x, y;
        x = evt.myOffsetX || evt.offsetX;
        y = evt.myOffsetY || evt.offsetY;
        return _this.searchPosition(x, y);
      };
      this.relativeMenu = new Menu(Res.tpls['area-relative-menu']);
      this.relativeMenu.J.addClass(this.name);
      this.relativeMenu.z = this.mainBg.z;
      this.relativeMenu.UI['res-point-box'].J.hide();
      _ref = this.data.resPoints;
      for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
        p = _ref[index];
        this.addResPoint(p, index);
      }
      _ref1 = this.data.movePoints;
      for (index = _j = 0, _len1 = _ref1.length; _j < _len1; index = ++_j) {
        mp = _ref1[index];
        this.addMovePoint(mp, index);
      }
      this.menu.show();
      this.relativeMenu.appendTo(this.menu.UI['relative-wrapper']);
      return this.camera.render(this.relativeMenu);
    };

    Place.prototype.searchPosition = function(x, y) {
      var bg, cx, cy, dx, dy, hEdge, realH, realW, realX, realY, s, scale, wEdge, _i, _j, _len, _len1, _ref, _ref1,
        _this = this;
      s = Utils.getSize();
      scale = 1.3;
      if (!this.scaledIn) {
        if (this.camera.lock) {
          return;
        }
        this.camera.lock = true;
        this.scaledIn = true;
        this.lastCameraPosition = {
          x: this.camera.x,
          y: this.camera.y
        };
        realW = s.width / scale;
        realH = s.height / scale;
        dx = x - s.width / 2;
        dy = y - s.height / 2;
        wEdge = s.width / 2 - realW / 2;
        hEdge = s.height / 2 - realH / 2;
        if (dx < -wEdge) {
          dx = -wEdge;
        }
        if (dx > wEdge) {
          dx = wEdge;
        }
        if (dy < -hEdge) {
          dy = -hEdge;
        }
        if (dy > hEdge) {
          dy = hEdge;
        }
        realX = this.currentX + dx;
        realY = 0 + dy;
        cx = this.camera.getOffsetPositionX(realX, this.mainBg);
        cy = this.camera.getOffsetPositionY(realY, this.mainBg);
        _ref = this.floatBgs;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          bg = _ref[_i];
          bg.animate({
            "transform.opacity": 0
          }, "fast");
        }
        this.menu.J.find(".autohide").fadeOut("fast", function() {
          return _this.relativeMenu.UI['res-point-box'].J.fadeIn("fast");
        });
        return this.camera.animate({
          x: cx,
          y: cy,
          scale: scale
        }, "fast", function() {
          return _this.camera.lock = false;
        });
      } else {
        if (this.camera.lock) {
          return;
        }
        this.camera.lock = true;
        this.scaledIn = false;
        _ref1 = this.floatBgs;
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          bg = _ref1[_j];
          bg.animate({
            "transform.opacity": 1
          }, "fast");
        }
        this.relativeMenu.UI['res-point-box'].J.fadeOut("fast", function() {
          return _this.menu.J.find(".autohide").fadeIn("fast");
        });
        return this.camera.animate({
          x: this.lastCameraPosition.x,
          y: this.lastCameraPosition.y,
          scale: 1
        }, "fast", function() {
          return _this.camera.lock = false;
        });
      }
    };

    Place.prototype.addResPoint = function(p, index) {
      var point, self;
      self = this;
      point = new ResPoint(this, this.relativeMenu.UI['res-point-tpl'].J.html(), p, index);
      point.appendTo(this.relativeMenu.UI['res-point-box']);
      return point.on("active", function(res) {
        return self.handleResPointActive(res);
      });
    };

    Place.prototype.addMovePoint = function(data, index) {
      var area, item, moveTarget, parts, self, x, y;
      area = this.area;
      parts = data.split(":");
      moveTarget = parts[0];
      x = parseInt(parts[1].split(",")[0]);
      y = parseInt(parts[1].split(",")[1]);
      item = new Suzaku.Widget(this.relativeMenu.UI['move-point-tpl'].innerHTML);
      if (moveTarget === "exit") {
        item.UI.target.J.text("离开");
      } else {
        item.UI.target.J.text(this.area.originData.places[moveTarget].name);
      }
      item.dom.target = moveTarget;
      item.x = x;
      item.y = y;
      item.J.addClass("mp-" + moveTarget);
      item.J.css({
        left: "" + x + "px",
        top: "" + y + "px"
      });
      item.appendTo(this.relativeMenu.UI['move-point-box']);
      self = this;
      return item.dom.onclick = function(evt) {
        var _this = this;
        evt.myOffsetX = evt.offsetX + item.x - self.currentX;
        evt.myOffsetY = evt.offsetY + item.y;
        return self.setCallback(300, function() {
          return area.enterPlace(_this.target);
        });
      };
    };

    Place.prototype.handleResPointActive = function(res) {
      var box;
      if (res.type === "item") {
        return this.emit("getItem", res.item);
      } else if (res.type === "monster") {
        return this.encounterMonster(res.monsters);
      } else if (res.type === "empty") {
        box = new GatherResaultBox();
        return box.show();
      } else {
        if (GameConfig.debug) {
          return console.error("invailid res type of res point :" + res);
        }
      }
    };

    Place.prototype.encounterMonster = function(monsters) {
      console.log("encounter monsters:", monsters);
      return this.area.initBattlefield(monsters);
    };

    return Place;

  })(Layer);

  window.Area = (function(_super) {
    __extends(Area, _super);

    function Area(game, areaName) {
      Area.__super__.constructor.call(this, game);
      this.game = game;
      this.name = areaName;
      this.data = game.db.areas.get(areaName);
      this.originData = this.data;
      this.backpackMenu = new Backpack(game, "gatherArea");
      console.log(this);
      this.enterPlace("entry");
    }

    Area.prototype.initBattlefield = function(monsters) {
      var bf, data,
        _this = this;
      data = {
        monsters: monsters,
        bg: this.data.battlefieldBg
      };
      this.game.saveStage();
      bf = this.game.switchStage("battle", data);
      console.log(bf);
      return bf.on("win", function() {
        AudioManager.play("home");
        _this.game.restoreStage();
        _this.emit("battleWin");
        _this.currentPlace.emit("battleWin");
        return _this.currentPlace.menu.show();
      });
    };

    Area.prototype.enterPlace = function(placeName) {
      var placeData,
        _this = this;
      if (placeName === "exit") {
        return this.game.switchStage("worldMap");
      }
      placeData = this.data.places[placeName];
      if (!placeData) {
        console.error("no place:" + placeName);
      }
      this.currentPlace = new Place(this, this.game.db, placeName, placeData);
      this.clearDrawQueue();
      this.drawQueueAddAfter(this.currentPlace);
      this.currentPlace.on("getItem", function(playerItem) {
        return _this.getItem(playerItem);
      });
      return this.currentPlace.on("showBackpack", function() {
        return _this.showBackpack();
      });
    };

    Area.prototype.showBackpack = function() {
      var self;
      console.log("show backpack");
      console.log(this.backpackMenu);
      self = this;
      this.backpackMenu.on("close", function() {
        self.currentPlace.onShow = true;
        return self.backpackMenu.hide(function() {
          return self.currentPlace.menu.show();
        });
      });
      return this.backpackMenu.show(function() {
        return self.currentPlace.onShow = false;
      });
    };

    Area.prototype.getItem = function(playerItem) {
      var box;
      console.log(playerItem);
      this.game.player.getItem("backpack", playerItem);
      box = new GatherResaultBox(playerItem);
      return box.show();
    };

    Area.prototype.tick = function() {
      if (this.currentPlace.tick) {
        return this.currentPlace.tick();
      }
    };

    return Area;

  })(Stage);

}).call(this);
