// Generated by CoffeeScript 1.6.3
(function() {
  var GuildMenu, MissionDetailsBox, MissionListItem,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MissionListItem = (function(_super) {
    __extends(MissionListItem, _super);

    function MissionListItem(tpl, missionData, menu) {
      MissionListItem.__super__.constructor.call(this, tpl);
      this.menu = menu;
    }

    return MissionListItem;

  })(Widget);

  MissionDetailsBox = (function(_super) {
    __extends(MissionDetailsBox, _super);

    function MissionDetailsBox(tpl, menu) {
      MissionDetailsBox.__super__.constructor.call(this, tpl);
      this.menu = menu;
    }

    MissionDetailsBox.prototype.showMissionDetails = function(widget) {
      var data;
      data = widget.missionData;
      this.UI.title.J.text(data.title);
      return this.UI.description.J.text(data.title);
    };

    return MissionDetailsBox;

  })(Widget);

  GuildMenu = (function(_super) {
    __extends(GuildMenu, _super);

    function GuildMenu(guild) {
      var _this = this;
      this.guild = guild;
      GuildMenu.__super__.constructor.call(this, Res.tpls['guild-menu']);
      this.detailsBox = new MissionDetailsBox(this.UI['mission-details-box'], this);
      this.listItems = [];
      this.UI['service-mission'].onclick = function() {
        return _this.initMissions();
      };
      this.UI['service-conversation'].onclick = function() {
        return guild.conversation();
      };
      this.UI['exit'].onclick = function() {
        return guild.exit();
      };
      this.UI['completed-mission'].onclick = function() {
        return _this.completedMissionMode();
      };
      this.UI['current-mission'].onclick = function() {
        return _this.currentMissionMode();
      };
      this.UI['end-mission'].onclick = function() {
        _this.guild.showServiceDialog();
        return _this.showServiceOptions();
      };
      this.show();
    }

    GuildMenu.prototype.removeListItem = function(item) {
      var i, newArr, _i, _len, _ref;
      newArr = [];
      _ref = this.listItems;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        if (i !== item) {
          newArr.push(i);
        } else {
          i.J.slideUp("fast", function() {
            return $(this).remove();
          });
        }
      }
      return this.listItems = newArr;
    };

    GuildMenu.prototype.initMissions = function() {
      this.hideServiceOptions();
      this.guild.dialogBox.hide();
      this.UI['mission-details-box'].J.hide();
      return this.UI['mission-box'].J.fadeIn("fast");
    };

    GuildMenu.prototype.showServiceOptions = function() {
      this.UI['mission-box'].J.fadeOut("fast");
      return this.UI['service-options'].J.fadeIn("fast");
    };

    GuildMenu.prototype.hideServiceOptions = function() {
      return this.UI['service-options'].J.fadeOut("fast");
    };

    GuildMenu.prototype.currentMissionMode = function() {
      var missions;
      missions = this.guild.missionManager.getMissions("current");
      return this.addItems(missions);
    };

    GuildMenu.prototype.completedMissionMode = function() {
      var missions;
      missions = this.guild.missionManager.getMissions("completed");
      return this.addItems(missions);
    };

    GuildMenu.prototype.addItems = function(items) {
      var playerThing, w, _i, _len, _results;
      console.log(items);
      this.listItems = [];
      this.UI['item-list'].J.html("");
      _results = [];
      for (_i = 0, _len = items.length; _i < _len; _i++) {
        playerThing = items[_i];
        w = new MissionListItem(this.UI['list-item-tpl'].innerHTML, playerThing, this);
        w.appendTo(this.UI['item-list']);
        _results.push(this.listItems.push(w));
      }
      return _results;
    };

    return GuildMenu;

  })(Menu);

  window.Guild = (function(_super) {
    __extends(Guild, _super);

    function Guild(game) {
      Stage.call(this, game);
      this.db = game.db;
      this.originData = this.db.shops.get("adventurerGuild");
      this.player = this.game.player;
      this.relationship = this.player.relationships[this.originData.npc];
      this.bg = new Layer(Res.imgs[this.originData.bg]);
      this.drawQueueAdd(this.bg);
      this.menu = new GuildMenu(this);
      this.initWelcomDialog();
    }

    return Guild;

  })(Shop);

}).call(this);
