// Generated by CoffeeScript 1.6.2
(function() {
  var FirstFloor, SecondFloor,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FirstFloor = (function(_super) {
    __extends(FirstFloor, _super);

    function FirstFloor(home) {
      var _this = this;

      FirstFloor.__super__.constructor.apply(this, arguments);
      this.home = home;
      this.menu = new Menu(Res.tpls["home-1st-floor"]);
      this.setImg(Res.imgs.homeDown);
      this.menu.UI.upstairs.onclick = function() {
        return _this.home.goUp();
      };
      this.menu.UI.exit.onclick = function() {
        return _this.home.exit();
      };
    }

    FirstFloor.prototype.show = function() {
      this.fadeIn("fast");
      return this.menu.show();
    };

    return FirstFloor;

  })(Layer);

  SecondFloor = (function(_super) {
    __extends(SecondFloor, _super);

    function SecondFloor(home) {
      var _this = this;

      SecondFloor.__super__.constructor.apply(this, arguments);
      this.home = home;
      this.y = -Utils.getSize().height;
      this.menu = new Menu(Res.tpls["home-2nd-floor"]);
      this.setImg(Res.imgs.homeUp);
      this.menu.UI['work-table'].onclick = function() {
        return _this.showWorkTable();
      };
      this.menu.UI.downstairs.onclick = function() {
        return _this.home.goDown();
      };
    }

    SecondFloor.prototype.showWorkTable = function() {
      var worktable,
        _this = this;

      worktable = new Worktable(this.home);
      this.onshow = false;
      this.home.drawQueueAddAfter(worktable);
      return worktable.on("close", function() {
        _this.home.drawQueueRemove(worktable);
        _this.onshow = true;
        return _this.menu.show();
      });
    };

    return SecondFloor;

  })(Layer);

  window.Home = (function(_super) {
    __extends(Home, _super);

    function Home(game) {
      Home.__super__.constructor.call(this);
      this.game = game;
      this.camera = new Camera();
      this.drawQueueAddAfter(this.camera);
      this.firstFloor = new FirstFloor(this);
      this.secondFloor = new SecondFloor(this);
      this.camera.render(this.firstFloor, this.secondFloor);
      this.firstFloor.show();
    }

    Home.prototype.goUp = function() {
      var s,
        _this = this;

      s = Utils.getSize();
      this.firstFloor.menu.hide();
      this.firstFloor.animate({
        y: s.height
      }, "normal");
      return this.secondFloor.animate({
        y: 0
      }, "normal", function() {
        return _this.secondFloor.menu.show();
      });
    };

    Home.prototype.goDown = function() {
      var s,
        _this = this;

      s = Utils.getSize();
      this.secondFloor.menu.hide();
      this.secondFloor.animate({
        y: -s.height
      }, "normal");
      return this.firstFloor.animate({
        y: 0
      }, "normal", function() {
        return _this.firstFloor.menu.show();
      });
    };

    Home.prototype.exit = function() {
      this.clearDrawQueue();
      return this.game.switchStage("worldMap");
    };

    return Home;

  })(Stage);

}).call(this);
