// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Things = (function(_super) {
    __extends(Things, _super);

    function Things(name, data) {
      Things.__super__.constructor.apply(this, arguments);
      this.data = data;
      this.name = name;
      this.dspName = data.name;
      if (data.img) {
        this.img = Res.imgs[data.img];
      } else {
        this.img = null;
      }
    }

    return Things;

  })(Suzaku.EventEmitter);

  window.GatherItem = (function(_super) {
    __extends(GatherItem, _super);

    function GatherItem(name, data) {
      GatherItem.__super__.constructor.call(this, name, data);
    }

    GatherItem.prototype.getGatherDataByPlace = function(area, place) {
      var arr, arr2, gatherData, placeGatherData, theArea, _i, _j, _len, _len1, _ref, _ref1;
      _ref = itemData.gather;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        gatherData = _ref[_i];
        arr = gatherData.split(" ");
        theArea = arr[0];
        if (theArea !== area) {
          continue;
        }
        _ref1 = arr[1].split(",");
        for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
          placeGatherData = _ref1[_j];
          arr2 = placeGatherData.split(".");
          if (arr2[0] !== place) {
            continue;
          }
          return {
            resPoint: parseInt(arr2[1])
          };
        }
      }
      return false;
    };

    GatherItem.prototype.tryGather = function(data) {
      return true;
    };

    return GatherItem;

  })(Things);

}).call(this);
