// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Things = (function(_super) {

    __extends(Things, _super);

    function Things(name, data, type) {
      Things.__super__.constructor.call(this);
      this.originData = data;
      this.name = name;
      this.dspName = data.name;
      this.type = type;
      if (data.img) {
        this.img = Res.imgs[data.img];
      } else {
        this.img = null;
      }
    }

    return Things;

  })(EventEmitter);

  window.PlayerItem = (function(_super) {

    __extends(PlayerItem, _super);

    function PlayerItem(name, originData, number) {
      var arr, t, _i, _len, _ref;
      PlayerItem.__super__.constructor.call(this, name, originData, "item");
      this.number = number;
      this.traits = {};
      _ref = originData.traits;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        t = _ref[_i];
        arr = t.split(":");
        this.traits[arr[0]] = parseInt(arr[1]);
      }
    }

    return PlayerItem;

  })(Things);

  window.PlayerSupplies = (function(_super) {

    __extends(PlayerSupplies, _super);

    function PlayerSupplies(name, originData, traitValue) {
      PlayerSupplies.__super__.constructor.call(this, name, originData, "supplies");
      this.traitValue = traitValue;
      this.traitName = originData.traitName;
      this.traits = {};
      this.traits[originData.traitName] = this.traitValue;
    }

    return PlayerSupplies;

  })(Things);

  window.PlayerEquipment = (function(_super) {

    __extends(PlayerEquipment, _super);

    function PlayerEquipment() {}

    return PlayerEquipment;

  })(Things);

  window.GatherItem = (function(_super) {

    __extends(GatherItem, _super);

    function GatherItem(name, data) {
      GatherItem.__super__.constructor.call(this, name, data, "item");
    }

    GatherItem.prototype.getGatherData = function() {
      return true;
    };

    GatherItem.prototype.tryGather = function(data) {
      return 1;
    };

    return GatherItem;

  })(Things);

}).call(this);
