// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.MissionManager = (function(_super) {
    __extends(MissionManager, _super);

    function MissionManager(game) {
      MissionManager.__super__.constructor.call(this, null);
      this.game = game;
      this.missions = [];
    }

    return MissionManager;

  })(EventEmitter);

}).call(this);
