// Generated by CoffeeScript 1.6.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.StartMenu = (function(_super) {

    __extends(StartMenu, _super);

    function StartMenu(game) {
      StartMenu.__super__.constructor.call(this, game);
      this.menu = new Menu(Res.tpls['start-menu']);
      this.initMenu();
    }

    StartMenu.prototype.initMenu = function() {
      var _this = this;
      $(".logo-holder").animate({
        opacity: "1"
      }, 1000);
      this.menu.UI["logo-line"].J.animate({
        width: "+=620px"
      }, 800, function() {
        _this.menu.UI["logo-bg"].J.animate({
          opacity: "1"
        }, 1500);
        return _this.menu.UI["logo-text"].J.animate({
          opacity: "1",
          right: "+=80px"
        }, 1500, function() {
          return _this.menu.UI["start-but"].J.show().animate({
            opacity: "1"
          }, 1000);
        });
      });
      this.menu.UI.start.onclick = function() {
        var lastStage;
        console.log("start game btn click");
        lastStage = _this.game.player.data.lastStage;
        return _this.game.switchStage(lastStage);
      };
      this.menu.UI.test.onclick = function() {
        console.log("start game btn click");
        return _this.game.switchStage("test");
      };
      this.menu.show();
      console.log(this.menu);
      return this.menu.UI["start-but"].onclick = function() {
        console.log("start-but click");
        _this.menu.UI["start-but"].J.fadeOut("fast");
        _this.menu.UI["sub-btn-list"].J.fadeIn("slow");
        return _this.menu.UI["logo-holder"].J.animate({
          bottom: "100px"
        }, 500, function() {
          return console.log("logo animate finish");
        });
      };
    };

    return StartMenu;

  })(Stage);

}).call(this);
