// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.StartMenu = (function(_super) {
    __extends(StartMenu, _super);

    function StartMenu(game) {
      StartMenu.__super__.constructor.call(this, game);
      this.menu = new Menu(Res.tpls['start-menu']);
      this.initMenu();
    }

    StartMenu.prototype.initMenu = function() {
      var but, _i, _len, _ref, _results,
        _this = this;
      $(".logo-holder").animate({
        opacity: "1"
      }, 1000);
      this.menu.UI["logo-line"].J.animate({
        width: "+=620px"
      }, 800, function() {
        _this.menu.UI["logo-bg"].J.animate({
          opacity: "1"
        }, 1500);
        _this.menu.UI["logo-text"].J.animate({
          opacity: "1",
          right: "+=80px"
        }, 1500);
        return _this.menu.UI["start-but"].J.show().animate({
          opacity: "1"
        }, 1000);
      });
      this.menu.UI.start.onclick = function() {
        var lastStage;
        console.log("start game btn click");
        window.myAudio.play("startClick");
        lastStage = _this.game.player.data.lastStage;
        return _this.game.switchStage(lastStage);
      };
      this.menu.UI.test.onclick = function() {
        console.log("start game btn click");
        window.myAudio.play("startClick");
        return _this.game.switchStage("test");
      };
      this.menu.show();
      console.log(this.menu);
      this.menu.UI["start-but"].onclick = function() {
        return _this.showSubMenu();
      };
      _ref = document.getElementsByTagName("button");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        but = _ref[_i];
        _results.push(but.onmouseover = function() {
          return window.myAudio.play("sfxStartCusor");
        });
      }
      return _results;
    };

    StartMenu.prototype.showSubMenu = function() {
      var _this = this;
      window.myAudio.play("startClick");
      this.menu.UI["logo-holder"].J.animate({
        bottom: "100px"
      }, 500);
      return this.menu.UI["start-but"].J.fadeOut("fast", function() {
        var J, animateBtn, dom, index, _i, _len, _ref, _results;
        animateBtn = function(btnJ) {
          return window.setTimeout((function() {
            return btnJ.animate({
              right: "+=150px",
              opacity: "1"
            }, 500);
          }), index * 60);
        };
        _this.menu.UI["sub-btn-list"].J.show();
        _ref = _this.menu.UI["sub-btn-list"].J.find(".start-but");
        _results = [];
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          dom = _ref[index];
          J = $(dom);
          J.css("right", "-=150px");
          _results.push(animateBtn(J));
        }
        return _results;
      });
    };

    return StartMenu;

  })(Stage);

}).call(this);
