// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.StartMenu = (function(_super) {
    __extends(StartMenu, _super);

    function StartMenu(game) {
      var _this = this;
      StartMenu.__super__.constructor.call(this, game);
      this.menu = new Menu(Res.tpls['start-menu']);
      this.menu.UI.start.onclick = function() {
        var lastStage;
        console.log("start game btn click");
        lastStage = _this.game.playerData.lastStage;
        return _this.game.switchStage(lastStage);
      };
      this.menu.show();
      console.log(this.menu);
    }

    return StartMenu;

  })(Stage);

}).call(this);
