// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.StoryManager = (function(_super) {
    __extends(StoryManager, _super);

    function StoryManager() {
      this.storyData = Res.tpls["story"];
      this.storys = {};
      this.initStoryData();
    }

    StoryManager.prototype.initStoryData = function() {
      return console.log("init story data");
    };

    StoryManager.prototype.showStory = function(name) {
      return console.log("show story", name);
    };

    return StoryManager;

  })(EventEmitter);

}).call(this);
