// Generated by CoffeeScript 1.6.3
(function() {
  var TaskManager,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  TaskManager = (function(_super) {
    __extends(TaskManager, _super);

    function TaskManager() {
      this.tasks = [];
    }

    return TaskManager;

  })(EventEmitter);

}).call(this);
