// Generated by CoffeeScript 1.6.3
(function() {
  var name;

  window.Utils = {
    getSize: function() {},
    drawRoundRect: function(context, x, y, w, h, r1, r2, r3, r4) {
      if (typeof r2 === "undefined") {
        r2 = r1;
        r3 = r1;
        r4 = r1;
      }
      context.beginPath();
      context.moveTo(x + r1, y);
      context.arcTo(x + w, y, x + w, y + h, r2);
      context.arcTo(x + w, y + h, x, y + h, r3);
      context.arcTo(x, y + h, x, y, r4);
      context.arcTo(x, y, x + w, y, r1);
      context.closePath();
      return context;
    },
    setCSS3Attr: function(dom, name, value) {
      var J, obj;
      J = $(dom);
      obj = {};
      obj["" + name] = value;
      obj["-webkit-" + name] = value;
      obj["-o-" + name] = value;
      obj["-ms-" + name] = value;
      obj["-moz-" + name] = value;
      return J.css(obj);
    },
    getKey: function(s) {
      var c, index, sum, _i, _len;
      sum = 0;
      for (index = _i = 0, _len = s.length; _i < _len; index = ++_i) {
        c = s[index];
        sum += s.charCodeAt(index);
      }
      return parseInt(sum << 3 | 555 % 10000);
    }
  };

  for (name in Suzaku.Utils) {
    window.Utils[name] = Suzaku.Utils[name];
  }

}).call(this);
