// Generated by CoffeeScript 1.6.3
(function() {
  var name;

  window.Dict = {
    QualityLevel: [30, 100, 200, 300, 500, 800],
    TraitsName: {
      life: "生命",
      fire: "火焰",
      water: "水",
      wind: "风",
      earth: "地",
      poison: "毒药",
      clear: "净化"
    }
  };

  window.Utils = {
    getSize: function() {},
    drawRoundRect: function(context, x, y, w, h, r1, r2, r3, r4) {
      if (typeof r2 === "undefined") {
        r2 = r1;
        r3 = r1;
        r4 = r1;
      }
      context.beginPath();
      context.moveTo(x + r1, y);
      context.arcTo(x + w, y, x + w, y + h, r2);
      context.arcTo(x + w, y + h, x, y + h, r3);
      context.arcTo(x, y + h, x, y, r4);
      context.arcTo(x, y, x + w, y, r1);
      context.closePath();
      return context;
    },
    setCSS3Attr: function(dom, name, value) {
      var J, obj;
      J = $(dom);
      obj = {};
      obj["" + name] = value;
      obj["-webkit-" + name] = value;
      obj["-o-" + name] = value;
      obj["-ms-" + name] = value;
      obj["-moz-" + name] = value;
      return J.css(obj);
    }
  };

  for (name in Suzaku.Utils) {
    window.Utils[name] = Suzaku.Utils[name];
  }

}).call(this);
