// Generated by CoffeeScript 1.6.3
(function() {
  var WorktableMenu,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  WorktableMenu = (function(_super) {
    __extends(WorktableMenu, _super);

    function WorktableMenu(tpl, worktable) {
      var _this = this;
      WorktableMenu.__super__.constructor.call(this, tpl);
      this.worktable = worktable;
      this.UI['exit-btn'].onclick = function() {
        return _this.worktable.close();
      };
    }

    return WorktableMenu;

  })(Menu);

  window.Worktable = (function(_super) {
    __extends(Worktable, _super);

    function Worktable(home) {
      Worktable.__super__.constructor.apply(this, arguments);
      this.home = home;
      this.floor = home.secondFloor;
      this.menu = new WorktableMenu(Res.tpls['worktable-menu'], this);
      this.menu.show();
    }

    Worktable.prototype.close = function() {
      var _this = this;
      this.menu.hide();
      return this.fadeOut(150, function() {
        return _this.emit("close");
      });
    };

    return Worktable;

  })(Layer);

}).call(this);
