// Generated by CoffeeScript 1.6.3
(function() {
  var Fs, Http, MainHandler, Path, Url, WriteErr, WriteFile, config, currentPath, server;

  config = {
    port: 8001,
    defaultPathname: "/index.html",
    Expires: {
      fileMatch: /|png|jpg|gif|css|js|html|/ig,
      maxAge: 60 * 60 * 24 * 365
    },
    MIMETypes: {
      "css": "text/css",
      "gif": "image/gif",
      "html": "text/html",
      "ico": "image/x-icon",
      "jpeg": "image/jpeg",
      "jpg": "image/jpeg",
      "js": "text/javascript",
      "json": "application/json",
      "pdf": "application/pdf",
      "png": "image/png",
      "svg": "image/svg+xml",
      "swf": "application/x-shockwave-flash",
      "tiff": "image/tiff",
      "txt": "text/plain",
      "wav": "audio/x-wav",
      "wma": "audio/x-ms-wma",
      "wmv": "video/x-ms-wmv",
      "xml": "text/xml",
      'unknow': "text/plain"
    }
  };

  Http = require("http");

  Path = require("path");

  Url = require("url");

  Fs = require("fs");

  currentPath = __dirname;

  console.log(currentPath);

  WriteErr = function(err, res) {
    res.writeHead(500, {
      'Content-Type': 'text/plain'
    });
    return res.end(err);
  };

  WriteFile = function(realPath, type, res) {
    return Fs.readFile(realPath, "binary", function(err, file) {
      if (err) {
        return WriteErr(err, res);
      } else {
        res.writeHead(200, {
          'Content-Type': config.MIMETypes[type]
        });
        res.write(file, "binary");
        return res.end();
      }
    });
  };

  MainHandler = function(req, res) {
    var ext, pathname, realPath, type, urldata;
    urldata = Url.parse(req.url);
    pathname = urldata.pathname;
    if (pathname === "/") {
      pathname = config.defaultPathname;
    }
    realPath = "" + currentPath + "/../local" + pathname;
    ext = Path.extname(realPath);
    type = ext ? ext.slice(1) : 'unknown';
    return Fs.exists(realPath, function(ans) {
      var expires;
      if (ans === false) {
        res.writeHead(404, {
          'Content-Type': 'text/plain'
        });
        res.write("This request URL " + realPath + " was not found on this server.");
        res.end();
        return;
      }
      if (ext.match(config.Expires.fileMatch)) {
        expires = new Date();
        expires.setTime(expires.getTime() + config.Expires.maxAge * 1000);
        res.setHeader("Expires", expires.toUTCString());
        res.setHeader("Cache-Control", "max-age=" + config.Expires.maxAge);
        return Fs.stat(realPath, function(err, stat) {
          var lastModified;
          if (err) {
            return WriteErr(err, res);
          }
          lastModified = stat.mtime.toUTCString();
          res.setHeader("Last-Modified", lastModified);
          if (lastModified === req.headers['if-modified-since']) {
            res.writeHead(304, "Not Modified");
            return res.end();
          } else {
            return WriteFile(realPath, type, res);
          }
        });
      } else {
        return WriteFile(realPath, type, res);
      }
    });
  };

  server = Http.createServer(MainHandler);

  server.listen(config.port);

  console.log("server running at port:" + config.port);

}).call(this);
