// Generated by CoffeeScript 1.6.3
(function() {
  var AreasDB, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AreasDB = (function(_super) {
    __extends(AreasDB, _super);

    function AreasDB() {
      _ref = AreasDB.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    AreasDB.prototype.constructer = function() {};

    return AreasDB;

  })(SubDB);

}).call(this);
