class window.MonstersDB extends SubDB
  constructor:->
    super "monsters"
    @init()
  init:->
    @data =
      qq:
        name:"企鹅"
        sprite:"qq"
        statusValue:
          hp:100
          def:30
          spd:30
        skills:
          attack:
            damage:
              normal:30
              water:10
          waterball:
            turn:2
            damage:
              water:100
        drop:
          certain:[]
          random:null
      pig:
        name:"布塔猪"
        sprite:"pig"
        statusValue:
          hp:150
          def:30
          spd:30
        skills:
          attack:
            damage:
              normal:30
              water:10
          waterball:
            turn:2
            damage:
              water:100
        drop:
          certain:[]
          random:null
      slime:
        name:"史莱姆"
        sprite:"slime"
        statusValue:
          hp:60
          def:30
          spd:30
        skills:
          attack:
            damage:
              normal:30
              water:10
          waterball:
            turn:2
            damage:
              water:100
        drop:
          certain:["bluerose"]
          random:null
    
