class window.MonstersDB extends SubDB
  constructor:->
    super "monsters"
    @init()
  init:->
    @data =
      qq:
        name:"企鹅"
        sprite:"qq"
        attackSound:"qqHit"
        statusValue:
          hp:100
          def:10
          spd:30
        damage:
          normal:60
        drop:
          money:20
      iceQQ:
        name:"冰企鹅"
        sprite:"iceQQ"
        attackSound:"qqHit"
        statusValue:
          hp:150
          def:10
          spd:35
        damage:
          ice:80
        drop:
          money:15
      iceQQKing:
        name:"冰企鹅王"
        sprite:"iceQQ"
        attackSound:"qqHit"
        scale:1.3
        statusValue:
          hp:300
          def:20
          spd:35
        damage:
          ice:120
        drop:
          money:80
      pig:
        name:"布塔猪"
        sprite:"pig"
        attackSound:"pigHit"
        statusValue:
          hp:150
          def:10
          spd:30
        damage:
          normal:35
          impact:30
        drop:
          money:10
      icePig:
        name:"皮格猪"
        sprite:"icePig"
        attackSound:"pigHit"
        statusValue:
          hp:150
          def:20
          spd:30
        damage:
          normal:30
          ice:30
        drop:
          money:10
      icePigKing:
        name:"皮格猪王"
        sprite:"icePig"
        scale:1.2
        attackSound:"pigHit"
        statusValue:
          hp:300
          def:30
          spd:28
        damage:
          normal:40
          ice:50
        drop:
          money:100
      pigKing:
        name:"布塔猪王"
        sprite:"pigDark"
        scale:1.2
        attackSound:"pigHit"
        statusValue:
          hp:300
          def:30
          spd:28
        damage:
          impact:80
        drop:
          money:100
      slime:
        name:"史莱姆"
        sprite:"slime"
        attackSound:"slimeHit"
        statusValue:
          hp:50
          def:5
          spd:20
        damage:
          normal:40
        drop:
          money:5
      iceSlime:
        name:"蓝史莱姆"
        sprite:"iceSlime"
        attackSound:"slimeHit"
        statusValue:
          hp:80
          def:10
          spd:25
        damage:
          ice:40
        drop:
          money:10
