// Generated by CoffeeScript 1.6.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ThingsDB = (function(_super) {
    __extends(ThingsDB, _super);

    function ThingsDB() {
      ThingsDB.__super__.constructor.call(this, "things");
      this.items = new SubDB("things-items");
      this.supplies = new SubDB("things-supplies");
      this.equipment = new SubDB("things-equipments");
      console.log("fuck");
      this.initItems();
      this.initSupplies();
      console.log(this.supplies);
    }

    ThingsDB.prototype.get = function(name) {
      return this.items.get(name) || this.supplies.get(name) || this.equipments.get(name);
    };

    ThingsDB.prototype.initItems = function() {
      return this.items.data = {
        earthLow: {
          name: "双生蘑菇",
          description: "森林里面会生长的奇特蘑菇，有地属性的能量。",
          traits: ["earth:10"],
          gatherRequire: null
        },
        earthMid: {
          name: "发光石",
          description: "比较少见到的发光宝石，是很多地属性魔法的原料",
          traits: ["earth:50"],
          gatherRequire: null
        },
        earthHigh: {
          name: "圣甲虫琥珀",
          description: "只有在很极端的情况下才能保留下来的宝石，里面的圣甲虫充满了地属性的魔力",
          traits: ["earth:200"],
          gatherRequire: null
        },
        airLow: {
          name: "清晨的森林里面可以搜集到的神奇雾气，如果装在瓶子里面就不会化开",
          description: "",
          traits: ["air:20"],
          gatherRequire: null
        },
        fireLow: {
          name: "火焰苔藓",
          description: "一种富含火元素的植物，制作火药的时候会加入这样的粉末",
          traits: ["fire:15", "earth:8"]
        },
        fireMid: {
          name: "火榴石",
          description: "虽然纯度不高，但是也算是火元素的结晶，有比较搞的火元素含量",
          traits: ["fire:60"]
        },
        fireHight: {
          name: "龙吸袋",
          description: "巨龙喷射龙吸所用的器官的一部分，非常稀有",
          traits: ["fire:180"]
        },
        waterLow: {
          name: "湖水",
          description: "清澈的湖水，在森林中的小湖里面可以找到",
          traits: ["water:10"]
        },
        waterHigh: {
          name: "无尽之泉",
          description: "光放着就会有源源不断的水流出来，是一种非常神奇的素材",
          traits: ["water:150"]
        },
        iceLow: {
          name: "冰结晶",
          description: "冰元素稍微丰富一点的区域就能找到这样的结晶，用来保存食物非常有效",
          traits: ["ice:15"]
        },
        iceMid: {
          name: "蓝钻",
          description: "很多冰结晶能够生成一颗这样的宝石，冰元素含量不错",
          traits: ["ice:60"]
        },
        iceHigh: {
          name: "天河之尘",
          description: "非常稀有的一种陨石，虽然表面感受不到温度，但是冰元素的含量非常惊人",
          traits: ["ice:380", "minus:50"]
        },
        lifeLow: {
          name: "药草",
          description: "有治疗效果的药草，很多汉方药里都有它的成分",
          traits: ["life:16"]
        },
        lifeMid: {
          name: "生命之水",
          description: "擦在伤口上就能让伤口快速愈合的神奇泉水，生命元素很丰富",
          traits: ["life:55"]
        },
        minusLow: {
          name: "彼岸花",
          description: "生长在生和死的境界线之间的花，有种让人不悦的力量",
          traits: ["minus:20"]
        },
        minusMid: {
          name: "虚无碎片",
          description: "来自深渊的碎片，据说是魔法战争时期造成的大震动留下的遗产，负能量含量较高",
          traits: ["minus:80"]
        },
        spiritLow: {
          name: "妖精的羽毛",
          description: "魅惑的妖精翅膀上的羽毛，有一种光是看着就让人着迷的魔力",
          traits: ["spirit:30"]
        },
        spiritMid: {
          name: "梦魇之角",
          description: "梦魇偶尔会在现界中被找到，他们的角是强大的灵能和负能量来源",
          traits: ["spirit:180", "minus:120"]
        },
        timeLow: {
          name: "时之沙",
          description: "古代遗迹中出土的沙子，据说有操纵时间的神奇能量",
          traits: ["time:25"]
        },
        spaceLow: {
          name: "以太",
          description: "被称为“不存在之物”的神奇元素，配合适当的魔法能够左右空间",
          traits: ["space:20"]
        }
      };
    };

    ThingsDB.prototype.initSupplies = function() {
      return this.supplies.data = {
        healPotion: {
          name: "治疗药剂",
          description: "有治疗效果的药剂",
          traitName: "heal",
          active: {
            name: "治疗术",
            description: "回复一定数量的生命值",
            type: "heal",
            rate: 1
          },
          defense: {
            name: "回复结界",
            description: "制造一个结界，在受到攻击时回复生命值",
            sameWidthAttack: true
          }
        },
        muddyPotion: {
          name: "泥泞药剂",
          description: "会让人身上变得粘糊糊的药剂，看起来就很奇怪",
          traitName: "muddy",
          active: {
            name: "泥泞术",
            description: "降低敌人的行动速度",
            type: "debuff",
            effect: {
              spd: [0.9, 0.5]
            }
          },
          active: {
            name: "泥泞陷阱",
            description: "制造一个陷阱，在被攻击时将攻击者减速",
            sameWidthAttack: true
          }
        },
        firePotion: {
          name: "火焰药剂",
          description: "有火焰效果的药剂",
          traitName: "fire",
          active: {
            name: "火球术",
            description: "释放火球对单体目标进行攻击",
            type: "attack",
            sprite: null,
            damage: {
              normal: 2,
              fire: 5
            }
          },
          defense: {
            name: "火焰陷阱",
            description: "使用火焰包围身体，在受到攻击时对敌人造成火焰伤害",
            sameWidthAttack: true
          }
        },
        ironPotion: {
          name: "坚硬药剂",
          description: "",
          traitName: "iron",
          active: {
            name: "坚硬术",
            description: "提升自己的物理防御",
            type: "buff",
            effect: {
              normalDef: [1.3, 2]
            }
          }
        },
        explodePotion: {
          name: "爆炸药剂",
          traitName: "explode",
          active: {
            name: "引爆",
            description: "压缩敌人周围的空气一次引爆，造成爆炸伤害并点燃敌人",
            type: "attack",
            damage: {
              normal: 8,
              fire: 5
            },
            next: {
              type: "dot",
              damage: {
                fire: 3
              }
            }
          }
        },
        burnPotion: {
          name: "燃烧药剂",
          traitName: "burn",
          active: {
            name: "点燃",
            description: "点燃敌人，使其每次行动都受到火焰伤害",
            type: "dot",
            damage: {
              fire: 3
            }
          },
          active: {
            name: "火焰之环",
            description: "制造一个燃烧场，点燃攻击的敌人",
            sameWidthAttack: true
          }
        },
        corrosionPotion: {
          name: "腐蚀药剂",
          traitName: "corrosion",
          active: {
            name: "腐蚀术",
            description: "造成负能量伤害，并降低敌人物理防御",
            type: "attack",
            damage: {
              minus: 5
            },
            next: {
              type: "debuff",
              effect: {
                normalDef: [0.8, 0.3]
              }
            }
          },
          defense: {
            name: "腐化结界",
            description: "制造一个腐化结界",
            sameWidthAttack: true,
            rate: 0.3
          }
        },
        icePotion: {
          name: "冰霜药剂",
          traitName: "ice"
        },
        fogPotion: {
          name: "雾气药剂",
          traitName: "fog",
          active: {
            type: "debuff",
            name: "雾气召唤",
            description: "在敌人周围制造雾气，降低他们的精准",
            effect: {
              precision: [0.8, 0.5]
            }
          }
        },
        snowPotion: {
          name: "风雪药剂",
          traitName: "snow"
        },
        bravePotion: {
          name: "勇气药剂",
          traitName: "brave",
          active: {
            type: "buff",
            name: "勇气术",
            description: "增加自己的物理攻击力",
            effect: {
              precision: [1.5, 3]
            }
          }
        },
        cleanPotion: {
          name: "净化药剂",
          traitName: "clean"
        },
        poisonPotion: {
          name: "毒药"
        },
        stunPotion: {
          name: "晕眩药剂",
          traitName: "stun",
          active: {
            type: "debuff",
            name: "晕眩术",
            effect: {
              stun: true
            }
          }
        }
      };
    };

    return ThingsDB;

  })(SubDB);

}).call(this);
