// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.ThingsDB = (function(_super) {
    __extends(ThingsDB, _super);

    function ThingsDB() {
      ThingsDB.__super__.constructor.call(this, "things");
      this.items = new SubDB("things-items");
      this.supplies = new SubDB("things-supplies");
      this.equipment = new SubDB("things-equipments");
      console.log("fuck");
      this.initItems();
      this.initSupplies();
      console.log(this.supplies);
    }

    ThingsDB.prototype.get = function(name) {
      return this.items.get(name) || this.supplies.get(name) || this.equipments.get(name);
    };

    ThingsDB.prototype.initItems = function() {
      return this.items.data = {
        earthLow: {
          name: "双生蘑菇",
          description: "随处可见的石头，但是要采集的话还是得去森林吧",
          traits: ["earth:10"],
          gatherRequire: null
        },
        earthMid: {
          name: "发光石",
          description: "随处可见的石头，但是要采集的话还是得去森林吧",
          traits: ["earth:10"],
          gatherRequire: null
        },
        earthHigh: {
          name: "圣甲虫琥珀",
          description: "随处可见的石头，但是要采集的话还是得去森林吧",
          traits: ["earth:10"],
          gatherRequire: null
        },
        airMid: {
          name: "不化之雾",
          description: "随处可见的石头，但是要采集的话还是得去森林吧",
          traits: ["air:10"],
          gatherRequire: null
        },
        fireLow: {
          name: "火焰苔藓",
          description: "可以打火的石头，能够感受到微弱的火属性魔力",
          traits: ["fire:10", "earth:5"]
        },
        fireMid: {
          name: "火榴石",
          description: "可以打火的石头，能够感受到微弱的火属性魔力",
          traits: ["fire:10", "earth:5"]
        },
        fireHight: {
          name: "龙吸袋",
          description: "可以打火的石头，能够感受到微弱的火属性魔力",
          traits: ["fire:10", "earth:5"]
        },
        waterLow: {
          name: "湖水",
          description: "清澈的湖水，含有少量净化所需的元素",
          traits: ["water:90", "clear:3"]
        },
        waterHigh: {
          name: "无尽之泉",
          description: "清澈的湖水，含有少量净化所需的元素",
          traits: ["water:90", "clear:3"]
        },
        iceLow: {
          name: "冰结晶",
          description: "蓝色的玫瑰，在森林里的背光面会长。得小心它的刺",
          traits: ["water:8", "life:8"]
        },
        iceMid: {
          name: "蓝钻",
          description: "蓝色的玫瑰，在森林里的背光面会长。得小心它的刺",
          traits: ["water:8", "life:8"]
        },
        iceHigh: {
          name: "天河之尘",
          description: "蓝色的玫瑰，在森林里的背光面会长。得小心它的刺",
          traits: ["water:8", "life:8"]
        },
        lifeLow: {
          name: "药草",
          description: "有治疗效果的药草，很多药物里都有它的成分",
          traits: ["life:16"]
        },
        lifeMid: {
          name: "生命之水",
          description: "有治疗效果的药草，很多药物里都有它的成分",
          traits: ["life:16"]
        },
        minusLow: {
          name: "彼岸花",
          description: "有治疗效果的药草，很多药物里都有它的成分",
          traits: ["life:16"]
        },
        minusMid: {
          name: "虚无碎片",
          description: "有治疗效果的药草，很多药物里都有它的成分",
          traits: ["life:16"]
        },
        spiritLow: {
          name: "妖精的羽翼",
          description: "有治疗效果的药草，很多药物里都有它的成分",
          traits: ["life:16"]
        },
        spiritMid: {
          name: "梦魇之角",
          description: "有治疗效果的药草，很多药物里都有它的成分",
          traits: ["life:16"]
        },
        spiritMid: {
          name: "梦魇之角",
          description: "有治疗效果的药草，很多药物里都有它的成分",
          traits: ["life:16"]
        },
        timeLow: {
          name: "时之沙",
          description: "有治疗效果的药草，很多药物里都有它的成分",
          traits: ["life:16"]
        },
        spaceLow: {
          name: "以太",
          description: "有治疗效果的药草，很多药物里都有它的成分",
          traits: ["life:16"]
        }
      };
    };

    ThingsDB.prototype.initSupplies = function() {
      return this.supplies.data = {
        healPotion: {
          name: "治疗药剂",
          description: "有治疗效果的药剂",
          traitName: "heal",
          img: Res.imgs.waterLow,
          active: {
            name: "治疗术",
            description: "回复一定数量的生命值",
            type: "heal",
            rate: 1
          },
          defense: {
            name: "回复结界",
            description: "制造一个结界，在受到攻击时回复生命值",
            sameWidthAttack: true
          },
          img: null
        },
        muddyPotion: {
          name: "泥泞药剂",
          description: "会让人身上变得粘糊糊的药剂，看起来就很奇怪",
          img: Res.imgs.waterLow,
          traitNnname: "muddy",
          active: {
            name: "泥泞术",
            description: "降低敌人的行动速度",
            type: "debuff",
            effect: {
              spd: [0.9, 0.5]
            }
          },
          active: {
            name: "泥泞陷阱",
            description: "制造一个陷阱，在被攻击时将攻击者减速",
            sameWidthAttack: true
          }
        },
        firePotion: {
          name: "火焰药剂",
          img: Res.imgs.waterLow,
          description: "有火焰效果的药剂",
          traitName: "fire",
          active: {
            name: "火球术",
            description: "释放火球对单体目标进行攻击",
            type: "attack",
            sprite: null,
            damage: {
              normal: 2,
              fire: 5
            }
          },
          defense: {
            name: "火焰陷阱",
            description: "使用火焰包围身体，在受到攻击时对敌人造成火焰伤害",
            sameWidthAttack: true
          }
        },
        ironPotion: {
          name: "坚硬药剂",
          description: "",
          traitName: "iron",
          active: {
            name: "坚硬术",
            description: "提升自己的物理防御",
            type: "buff",
            effect: {
              normalDef: [1.3, 2]
            }
          }
        },
        explodePotion: {
          name: "爆炸药剂",
          traitName: "explode",
          active: {
            name: "引爆",
            description: "压缩敌人周围的空气一次引爆，造成爆炸伤害并点燃敌人",
            type: "attack",
            damage: {
              normal: 8,
              fire: 5
            },
            next: {
              type: "dot",
              damage: {
                fire: 3
              }
            }
          }
        },
        burnPotion: {
          name: "燃烧药剂",
          traitName: "burn",
          active: {
            name: "点燃",
            description: "点燃敌人，使其每次行动都受到火焰伤害",
            type: "dot",
            damage: {
              fire: 3
            }
          },
          active: {
            name: "火焰之环",
            description: "制造一个燃烧场，点燃攻击的敌人",
            sameWidthAttack: true
          }
        },
        corrosionPotion: {
          name: "腐蚀药剂",
          traitName: "corrosion",
          active: {
            name: "腐蚀术",
            description: "造成负能量伤害，并降低敌人物理防御",
            type: "attack",
            damage: {
              minus: 5
            },
            next: {
              type: "debuff",
              effect: {
                normalDef: [0.8, 0.3]
              }
            }
          },
          defense: {
            name: "腐化结界",
            description: "制造一个腐化结界",
            sameWidthAttack: true,
            rate: 0.3
          }
        },
        icePotion: {
          name: "冰霜药剂",
          traitName: "ice"
        },
        fogPotion: {
          name: "雾气药剂",
          traitName: "fog",
          active: {
            type: "debuff",
            name: "雾气召唤",
            description: "在敌人周围制造雾气，降低他们的精准",
            effect: {
              precision: [0.8, 0.5]
            }
          }
        },
        snowPotion: {
          name: "风雪药剂",
          traitName: "snow"
        },
        bravePotion: {
          name: "勇气药剂",
          traitName: "brave",
          active: {
            type: "buff",
            name: "勇气术",
            description: "增加自己的物理攻击力",
            effect: {
              precision: [1.5, 3]
            }
          }
        },
        cleanPotion: {
          name: "净化药剂",
          traitName: "clean"
        },
        poisonPotion: {
          name: "毒药"
        },
        stunPotion: {
          name: "晕眩药剂",
          traitName: "stun",
          active: {
            type: "debuff",
            name: "晕眩术",
            effect: {
              stun: true
            }
          }
        }
      };
    };

    return ThingsDB;

  })(SubDB);

}).call(this);
